[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
panic = "abort"
lto = true
strip = true
opt-level = "z"

[[bin]]
name = "exifrename"
path = "src/main.rs"
